language: android
jdk: oraclejdk8
os: linux

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-22

    # Emulator for the tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-preview-license-.+'

script:
  - ./gradlew clean assemble test -a

notifications:
  email: false

